name: Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        go_version: ['oldstable','stable']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
        check-latest: true

    - name: Tests
      run: go test -v -race -cover -coverprofile=coverage.out -covermode=atomic -coverpkg=. ./...


    - name: Update Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
        flag-name: Go-${{ matrix }}
        parallel: true

  # notifies Coveralls that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
